[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["multipart", "ws"] }
axum-macros = "0.4.1"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.39.3", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
tower = { version = "0.5.1", features = ["util"] }

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols

[dev-dependencies]
futures-util = { version = "0.3.31", features = ["sink"] }
reqwest = "0.12.8"
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
http-body-util = "0.1.2"
