name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a tag matching the pattern v*.*.* is pushed

jobs:
  build:
    runs-on: ${{ matrix.os }} # Define the operating system on which the job runs
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Define the operating system matrix
        arch: [x86_64] # Define the architecture matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the repository code

      - name: Set up Rust
        uses: actions-rs/toolchain@v1 # Set up the Rust toolchain
        with:
          toolchain: stable # Use the stable Rust toolchain
          profile: minimal # Use the minimal configuration file
          override: true # Override any existing Rust toolchain settings

      - name: Build project
        run: cargo build --release # Build the release version of the project

      # Upload build artifacts for Linux x86_64 platform
      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-latest-friendlyfire_server
          path: target/release/friendlyfire_server

      # Upload build artifacts for macOS x86_64 platform
      - name: Upload artifact (macOS)
        if: matrix.os == 'macos-latest' && matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v2
        with:
          name: macos-latest-friendlyfire_server
          path: target/release/friendlyfire_server

      # Upload build artifacts for Windows x86_64 platform
      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-latest' && matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v2
        with:
          name: windows-latest-friendlyfire_server
          path: target/release/friendlyfire_server.exe

  release:
    runs-on: ubuntu-latest # Define the job to run on Ubuntu
    needs: build # Depends on the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the repository code

      # Download build artifacts for Linux x86_64 platform
      - name: Download artifact (Linux-x86_64)
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest-friendlyfire_server
          path: artifacts/ubuntu

      # Download build artifacts for macOS x86_64 platform
      - name: Download artifact (macOS-x86_64)
        uses: actions/download-artifact@v2
        with:
          name: macos-latest-friendlyfire_server
          path: artifacts/macos

      # Download build artifacts for Windows x86_64 platform
      - name: Download artifact (Windows-x86_64)
        uses: actions/download-artifact@v2
        with:
          name: windows-latest-friendlyfire_server
          path: artifacts/windows

      - name: Create release
        id: create_release
        uses: actions/create-release@v1 # Create a GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Authenticate using GitHub token
        with:
          tag_name: ${{ github.ref }} # Use the pushed tag name
          release_name: Release ${{ github.ref }} # Use the pushed tag name as the release name
          body: |
            Changes in this Release
            - First Change
            - Second Change # Release notes
          draft: true # Whether it's a draft
          prerelease: false # Whether it's a prerelease

      # Upload Linux x86_64 build artifact to the release page
      - name: Upload Linux x86_64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Authenticate using GitHub token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Use the upload URL generated by the create release step
          asset_path: artifacts/ubuntu/friendlyfire_server # Path of the file to upload
          asset_name: friendlyfire_server-linux-x86_64 # Name of the file to upload
          asset_content_type: application/octet-stream # File content type

      # Upload macOS x86_64 build artifact to the release page
      - name: Upload macOS x86_64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Authenticate using GitHub token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Use the upload URL generated by the create release step
          asset_path: artifacts/macos/friendlyfire_server # Path of the file to upload
          asset_name: friendlyfire_server-macos-x86_64 # Name of the file to upload
          asset_content_type: application/octet-stream # File content type

      # Upload Windows x86_64 build artifact to the release page
      - name: Upload Windows x86_64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Authenticate using GitHub token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Use the upload URL generated by the create release step
          asset_path: artifacts/windows/friendlyfire_server.exe # Path of the file to upload
          asset_name: friendlyfire_server-windows-x86_64.exe # Name of the file to upload
          asset_content_type: application/octet-stream # File content type
